### ISSUE TITLE
node-pre-gyp encountering 404 error during `yarn install`

### ISSUE THREAD

**Issue by erinalahorlbeck** [mapbox/node-pre-gyp#460] opened 2019-05-21 01:38 UTC
I'm seeing some 404 errors when attempting to run `yarn install` in my project on Mac, which contains `node-pre-gyp` somewhere as a dependency. Never seen this problem before.

```
node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@0.10.0
node-pre-gyp info using node@12.1.0 | darwin | x64
node-pre-gyp info check checked for \"/[my-project-path]/node_modules/fsevents/lib/binding/Release/node-v72-darwin-x64/fse.node\" (not found)
node-pre-gyp http GET https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.2.4/fse-v1.2.4-node-v72-darwin-x64.tar.gz
node-pre-gyp http 404 https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.2.4/fse-v1.2.4-node-v72-darwin-x64.tar.gz
node-pre-gyp WARN Tried to download(404): https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.2.4/fse-v1.2.4-node-v72-darwin-x64.tar.gz 
node-pre-gyp WARN Pre-built binaries not found for fsevents@1.2.4 and node@12.1.0 (node-v72 ABI, unknown) (falling back to source compile with node-gyp) 
node-pre-gyp http 404 status code downloading tarball https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.2.4/fse-v1.2.4-node-v72-darwin-x64.tar.gz 
```

Have the binaries gone missing on AWS?

**Comment by MaTToX3** [comment] 2020-02-19 09:46
Same here.

node-pre-gyp http 404 https://node-precompiled-binaries.grpc.io/grpc/v1.20.0/node-v72-darwin-x64-unknown.tar.gz

Any workarounds? Cloned the old project and can't get it up and running.

**Comment by michaelpeterlee** [comment] 2021-12-07 22:00
Our old project refers `node-v93-darwin-x64-unknown.tar.gz` the `unknown` segment denotes mis-registration somewhere.

**Comment by springmeyer** [comment] 2021-12-07 22:40
Agree. `unknown` seems to indicate a misconfiguration by the application using node-pre-gyp (rather than a problem with node-pre-gyp itself). So, i'll close this issue - I recommend opening issues with the specific module/application that is using node-pre-gyp if others hit this problem in the future.

As far as the cause of the original issue that @erinalahorlbeck posted about - it is also a problem with grpc not node-pre-gyp (but I don't see `unknown` involved). Rather in that case I think @erinalahorlbeck was attempting to install with a node version or operating system that grpc had not yet provided binaries for.

**Closed by springmeyer** 2021-12-07 22:40 UTC
