### ISSUE TITLE
node-pre-gyp with npm scoped packages

### ISSUE THREAD

**Issue by jakepruitt** [mapbox/node-pre-gyp#228] opened 2016-07-18 14:17 UTC
Hey @springmeyer - question about conventions with using [scoped packages in npm](https://docs.npmjs.com/misc/scope). I recently published [vtinfo](https://github.com/mapbox/vtinfo) under `@mapbox/vtinfo` to npm, but node-pre-gyp used the `name` property in the `package.json` during the `node-pre-gyp publish` step. The package was published to:

```
https://mapbox-node-binary.s3.amazonaws.com/vtinfo/v0.0.1/Release/node-v46-darwin-x64.tar.gz
```

But when the `npm install @mapbox/vtinfo --fallback-to-build` was called, node-pre-gyp looked for the package at:

```
https://mapbox-node-binary.s3.amazonaws.com/@mapbox/vtinfo/v0.0.1/Release/node-v46-darwin-x64.tar.gz
```

As a temporary hack, I changed the `package.json` `"name"` property to `"@mapbox/vtinfo"`, which allowd node-pre-gyp to publish it to the right place, (the second url).

Should we keep it this way or change node-pre-gyp to determine the install url from the `"name"` property instead of the module name on npm when they conflict?

cc/ @mapsam

**Comment by mapsam** [comment] 2016-07-18 17:42
@jakepruitt thanks for bringing this up! I believe updating the `name` property in the `package.json` [is the way to create a scoped package]https://docs.npmjs.com/getting-started/scoped-packages#initializing-a-scoped-package) - so this isn't a hack at all, and is something that will be standard. 

I was messing around with scopes in `vtinfo` and published without actually committing my updated package.json to GitHub. My mistake!

**Comment by springmeyer** [comment] 2016-10-24 20:32
Per chat I think there was not a bug in the end, but just a misunderstanding. Closing.

**Closed by springmeyer** 2016-10-24 20:32 UTC
