### ISSUE TITLE
node-pre-gyp fails to find node-gyp properly

### ISSUE THREAD

**Issue by nicolasnoble** [mapbox/node-pre-gyp#365] opened 2018-04-09 21:31 UTC
Apparently, since a few versions of npm, `node-gyp` isn't a direct dependency of `npm` anymore, it's a transitive dependency of the package `npm-lifecycle`.

As a result, the probing function `which_node_gyp` in the file [compile.js](https://github.com/mapbox/node-pre-gyp/blob/master/lib/util/compile.js) fails to find the node-gyp binary.

As a resolution, I would recommend probing for both `node_modules/node-gyp/bin/node-gyp.js` and `node_modules/npm-lifecycle/node_modules/node-gyp/bin/node-gyp.js`. Maybe even just probing the `node_modules/npm/bin/node-gyp-bin` directory instead, since this is what `npm` uses internally.

**Comment by mapsam** [comment] 2018-04-09 21:37
Hey @nicolasnoble - thanks for the issue! This is a duplicate of https://github.com/mapbox/node-pre-gyp/issues/362 so going to close. It appears even npm itself fails because of this change, so there's a fix in place over at https://github.com/npm/npm/pull/20276

I think the probing for node-gyp could be a good failsafe for situations like this in the future, though. Will add your idea to that ticket 😄

**Closed by mapsam** 2018-04-09 21:37 UTC
